# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chatbot-zhou997

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://zhou997.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f0bf447750be42b584bd79e25fc50fb1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_640875cbee40444699c24e187c878a8a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: zhou997.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f0bf447750be42b584bd79e25fc50fb1 }}/tgchatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chatbot-zhou997'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c7181b8943c8438fa248ed9069d30b36 }}
        images: 'zhou997.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f0bf447750be42b584bd79e25fc50fb1 }}/tgchatbot:${{ github.sha }}'